### ISSUE TITLE
Can't use: wrong or outdated ruby version/interpreter

### ISSUE THREAD

**Issue by linzehui** [wookayin/alfred-latex-symbols-workflow#4]
I downloaded the workflow and installed it. But my search query didn't work. Is there anything that I have to install first?

![image](https://user-images.githubusercontent.com/16056955/40097605-a66eb624-5909-11e8-9f20-337bbf166bdf.png)

**Comment by linzehui** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/16056955/40109948-49dc0a42-5931-11e8-8e8e-6fcbbd598321.png">

it appears, but I can't search anything .

**Comment by wookayin** [comment]
I guess you don't have a proper ruby installation. Find the workflow in the Alfred Preference Tab, and open the debugger log by clicking the bug-like button:

![image](https://user-images.githubusercontent.com/1009873/41450799-cf83d586-7037-11e8-8302-29519b55c975.png)

Which log messages do you see?

**Comment by wookayin** [comment]
The error message seems to be look like:

```
	2: from main.rb:12:in `<main>'
	1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- alfred (LoadError)
```

which happens because the `alfred` ruby gem doesn't exist for the specific version that is being executed. In the workflow, the path to ruby is set `/usr/bin/ruby`. If this path doesn't exist, the workflow will not work; in addition, even if it does but if ruby version is > 2.1 (which is quite likely as this workflow was written 2 years ago) the aforementioned error will occur.

I need to make the workflow automatically would fetch the correct dependencies regardless of the ruby version and interpreter being used.

**Comment by wookayin** [comment]
As a workaround until I fix the issue, you can do the following:

* Make sure that `ruby` is installed in your system (e.g. `/usr/bin/ruby`)
* Locate the workflow directory (Right-click on the workflow -- Open in Finder/Terminal to get the path)
* Open the terminal and go to the workflow directory. Then:
```
$ bundle install --standalone
```

Reference: [Rakefile#L36](https://github.com/wookayin/alfred-latex-symbols-workflow/blob/develop/Rakefile#L36)

**Comment by stex** [comment]
Since this gave me the idea of a `--standalone` bundle install initially for an own workflow, I'll leave my solution here for others coming from Google:

I added an additional "run script" in Alfred and placed it before the actual workflow logic:

```ruby
#!/usr/bin/env ruby

begin
  begin
    require_relative 'bundle/bundler/setup'
  rescue LoadError
    require 'bundler'
    Bundler.setup
  end
rescue Bundler::GemNotFound
  puts system("/usr/bin/env bundle install --standalone")
end
```

This ensures that the necessary gems are installed.

**Comment by sillybun** [comment]
I got the same error and fix it with the help from

https://github.com/zhaocai/alfred2-sourcetree-workflow/issues/7

```
ln -s "`pwd`/2.0.0" "`pwd`/2.6.0"
```

**Comment by cocoaaa** [comment]
Before running `$ bundle install --standalone` I needed to install [bundler](https://bundler.io/) first, by running:
`sudo gem install bundler`

**Comment by martinjnilsen** [comment]
As @sillybun commented above, you can use the answer provided in [this thread](https://github.com/zhaocai/alfred2-sourcetree-workflow/issues/7#issuecomment-633050353). The steps you will have to do is locate the workflow in finder (right click on workflow in Alfred settings will provide this option), create a terminal here, and cd into "./bundle/ruby", before you run:

```ln -s "`pwd`/2.0.0" "`pwd`/2.6.0"```

This worked for me on macOS Monterey (12.0.1)

If this do not fix your problem, I would use the debugger and check which version of Ruby the workflow tries to utilize (path is given in error message), and change the symbolic link accordingly

**Comment by wookayin** [comment]
I wasn't maintaining this package for such a long time and do understand that outdated ruby interpreter causes such a pain, preventing the workflow from working out-of-box. As such, I **completely rewrote** the workflow in Node.js.

Please uninstall the existing workflow (if any), and reinstall v1.0 using `npm`.
